### ISSUE TITLE
TypeError on yargs when using concurrently to start services

### ISSUE THREAD

**Issue by jchli** [open-cli-tools/concurrently#314]
Hello, we're running into an intermittent issue where we get a

`TypeError: shim$1.Parser.lookslikeNumber is not a function` error when trying to start up our services with: `concurrently "npm run local-server" "npm run l10n-watch"`. It looks like its coming from `yargs`.

We currently need to `npm uninstall concurrently && npm install concurrently` to "fix" it

The stacktrace:

```
/app-repo/node_modules/concurrently/node_modules/yargs/build/index.cjs:2804
        if (shim$1.Parser.lookslikeNumber(arg) &&
                          ^

TypeError: shim$1.Parser.lookslikeNumber is not a function
    at Object.Yargs.self._parsePositionalNumbers (app-repo/node_modules/concurrently/node_modules/yargs/build/index.cjs:2804:31)
    at Object.Yargs.self._postProcess (app-repo/node_modules/concurrently/node_modules/yargs/build/index.cjs:2787:25)
    at Object.parseArgs [as _parseArgs] (app-repo/node_modules/concurrently/node_modules/yargs/build/index.cjs:2774:21)
    at Object.get [as argv]] (app-repo/node_modules/concurrently/node_modules/yargs/build/index.cjs:2651:25)
    at Object.<anonymous> (app-repo/node_modules/concurrently/dist/bin/concurrently.js:170:5)

```

Version: concurrently@7.1.0

**Comment by gustavohenke** [comment]
Said new release is out now -- do you want to give it a try and report back, @jchli?

**Comment by paescuj** [comment]
Closing as I assume this has been fixed  Please open a new issue if the problem still exists

**Comment by BowlingX** [comment]
I'm having the same problem with `yargs` >= `17.6.1`, the last version that works is `17.6.0`.
