### ISSUE TITLE
Deprecation warning with Node 22

### ISSUE THREAD

**Issue by Urmeli0815** [open-cli-tools/concurrently#477]
After upgrading to Node 22 we get a deprecation warning `DEP0060` caused by the dependency `spawn-command`:

```
at module.exports (...\node_modules\spawn-command\lib\spawn-command.js:9)
at Proxy.start (...\node_modules\concurrently\dist\src\command.js:55:28)
...
```
The code that causes that is [this line](https://github.com/mmalecki/spawn-command/blob/master/lib/spawn-command.js#L9)

The [fix](https://nodejs.org/api/deprecations.html#DEP0060) looks trivial but `spawn-command` doesn't seem to be developed anymore. Maybe the functionality could be integrated in `concurrently`.

**Comment by gustavohenke** [comment]
Thanks for raising this. I agree that we can integrate it into concurrently.

**Comment by moritz-baecker-integra** [comment]
Are you sure, that you want to include the functionality into concurrently?
https://www.npmjs.com/package/spawn-command
seems to be active, because the problem got fixed

**Comment by PatrykKuniczak** [comment]
@gustavohenke Are you able to realase this soon?
I want to bump node to 22 on my project, but i don't want with this error :)

**Comment by theonlypwner** [comment]
mmalecki/spawn-command#9 was fixed recently, so all that really needed to be done was to bump `spawn-command` to `0.0.3`.

**Comment by gustavohenke** [comment]
Hi folks, sorry for the delay, this is now fixed in v9.0.0.
https://github.com/open-cli-tools/concurrently/releases/tag/v9.0.0

**Comment by Urmeli0815** [comment]
@gustavohenke Thanks for the release. The good news is that the warning is gone. The bad news is that I get a new one now :)

```
Generate source code (12 tasks) ...
 0% | ETA: 0s | 0/12(node:14748) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. MaxListenert
    at [kNewListener] (node:internal/event_target:562:17)
    at [kNewListener] (node:internal/abort_controller:268:24)
    at AbortSignal.addEventListener (node:internal/event_target:675:23)
    at mycheckout\node_modules\rxjs\dist\cjs\internal\observable\fromEvent.js:38:111
    at Observable._subscribe (mycheckout\node_modules\rxjs\dist\cjs\internal\observable\fromEvent.js:61:9)
    at Observable._trySubscribe (mycheckout\node_modules\rxjs\dist\cjs\internal\Observable.js:41:25)
    at mycheckout\node_modules\rxjs\dist\cjs\internal\Observable.js:35:31
    at Object.errorContext (mycheckout\node_modules\rxjs\dist\cjs\internal\util\errorContext.js:22:9)
    at Observable.subscribe (mycheckout\node_modules\rxjs\dist\cjs\internal\Observable.js:26:24)
    at Object.mergeInternals (mycheckout\node_modules\rxjs\dist\cjs\internal\operators\mergeInternals.js:56:12)
```

In my case I start over 300 tasks (in the worst case) using concurrently. But the warning appears as soon as I have more than 10 tasks. I also noticed that the `exited` property of these tasks never seems to be set, even when the task finished correctly.

**Comment by gustavohenke** [comment]
Ok, let's start a new issue for this one please

**Comment by Urmeli0815** [comment]
I created https://github.com/open-cli-tools/concurrently/issues/502.
