### ISSUE TITLE
`gcloud beta emulators pubsub start` fails with concurrently

### ISSUE THREAD

**Issue by jplumail** [open-cli-tools/concurrently#520]
# Description

A program fails when I run it with concurrently.
```
$ concurrently "gcloud beta emulators pubsub start"
```
My stack trace:
```
[0] Executing: /Users/jean/.local/google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=::1 --port=8598
[0] [pubsub] This is the Google Pub/Sub fake.
[0] [pubsub] Implementation may be incomplete or differ from the real system.
[0] [pubsub] déc. 13, 2024 11:02:01 AM com.google.cloud.pubsub.testing.v1.Main main
[0] [pubsub] INFOS: IAM integration is disabled. IAM policy methods and ACL checks are not supported
[0] [pubsub] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[0] [pubsub] SLF4J: Defaulting to no-operation (NOP) logger implementation
[0] [pubsub] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[0] [pubsub] Exception in thread "main" java.io.IOException: Failed to bind to address /0:0:0:0:0:0:0:1:0
[0] [pubsub]    at io.grpc.netty.NettyServer.start(NettyServer.java:333)
[0] [pubsub]    at io.grpc.internal.ServerImpl.start(ServerImpl.java:185)
[0] [pubsub]    at io.grpc.internal.ServerImpl.start(ServerImpl.java:94)
[0] [pubsub]    at io.gapi.emulators.grpc.GrpcServer.start(GrpcServer.java:169)
[0] [pubsub]    at com.google.cloud.pubsub.testing.v1.Main.main(Main.java:223)
[0] [pubsub] Caused by: java.net.SocketException: Protocol family unavailable
[0] [pubsub]    at sun.nio.ch.Net.bind0(Native Method)
[0] [pubsub]    at sun.nio.ch.Net.bind(Net.java:438)
[0] [pubsub]    at sun.nio.ch.Net.bind(Net.java:430)
[0] [pubsub]    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:225)
[0] [pubsub]    at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141)
[0] [pubsub]    at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:561)
[0] [pubsub]    at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1281)
[0] [pubsub]    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600)
[0] [pubsub]    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579)
[0] [pubsub]    at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:922)
[0] [pubsub]    at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:259)
[0] [pubsub]    at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:380)
[0] [pubsub]    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[0] [pubsub]    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[0] [pubsub]    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[0] [pubsub]    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[0] [pubsub]    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[0] [pubsub]    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[0] [pubsub]    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[0] [pubsub]    at java.lang.Thread.run(Thread.java:750)
```

# Expected Behavior

I expect this program to not fail, I can run it on my machine with no problem.

```
$ gcloud beta emulators pubsub start
Executing: /Users/jean/.local/google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=::1 --port=8647
[pubsub] This is the Google Pub/Sub fake.
[pubsub] Implementation may be incomplete or differ from the real system.
[pubsub] déc. 13, 2024 11:02:31 AM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFOS: IAM integration is disabled. IAM policy methods and ACL checks are not supported
[pubsub] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[pubsub] SLF4J: Defaulting to no-operation (NOP) logger implementation
[pubsub] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[pubsub] déc. 13, 2024 11:02:31 AM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFOS: Server started, listening on 8647
```

# Environment

MacOS Sonoma, Node v22.8.0, concurrently v9.1.0

# Reproduction

 First, [install gcloud cli](https://cloud.google.com/sdk/docs/install).
 Then:
 ```
$ gcloud components install pubsub-emulator
$ concurrently "gcloud beta emulators pubsub start"
```

**Comment by gustavohenke** [comment]
Hey.
I wasn't able to reproduce this, but I'm on Sequoia, instead of Sonoma. Tried both on Node 20 and 22.
Is there a chance that we're on different versions of gcloud, and there was a bug?

```
$ gcloud --version
Google Cloud SDK 504.0.1
beta 2024.12.19
bq 2.1.11
core 2024.12.19
gcloud-crc32c 1.0.0
gsutil 5.33
pubsub-emulator 0.8.17
```

That said, the fact that you're seeing a network issue is concerning, there aren't any network calls or env variables within concurrently that could have an effect like that.
Are you able to reproduce it consistently?

**Comment by jplumail** [comment]
I wasn't able to reproduce this issue !
I don't know what happened...
